import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <header className=" border-b bg-white top-0 sticky z-50">
          <Header />
        </header>
        <div className="bg-[#f4f2ed] flex-1 w-full">
          <main>{children}</main>
        </div>
        {/* Toaster */}
      </body>
    </html>
  );
}
